global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'self'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-test'
    static_configs:
      - targets: ['test_postgres_exporter:9187']
